---

- name: Set software information
  ansible.builtin.set_fact:
    software_to_uninstall: "/directory-that-should-not-exist"
    module_to_uninstall: "/directory-that-should-not-exist/module-that-should-not-exist.lua"

# Uninstall specified conda software and modules
- name: Removing software
  ansible.builtin.file:
    path: "{{ software_to_uninstall }}"
    state: absent
- name: Removing module
  ansible.builtin.file:
    path: "{{ module_to_uninstall }}"
    state: absent


