---
##################################################################################
# Spyder
##################################################################################

# Get vars from roles' vars/ directory
- name: Get package information
  ansible.builtin.set_fact:
    package: "{{ spyder.package }}"

- name: Set task variables
  ansible.builtin.set_fact:
    package_name: "{{ package.name }}"
    package_version: "{{ package.version }}"
    package_arch: "{{ package.arch }}"
    package_os: "{{ package.os }}"
    package_base_url: "{{ package.base_url }}"
    package_checksum: "{{ package.checksum }}"
    base_path: "{{ environments_path }}/dependencies/{{ package.name }}/{{ package.version }}"
    install_path: "{{ local_path }}/software/{{ package.name }}/{{ package.version }}"

- name: Set download link
  ansible.builtin.set_fact:
    package_url: "{{ package_base_url }}/v{{ package_version }}/Spyder-{{ package_os }}-{{ package_arch }}.sh"

- name: Create temporary directory to download package archive
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: temp_dir

- name: Download the package archive with SHA256 verification
  ansible.builtin.get_url:
    url: "{{ package_url }}"
    dest: "{{ temp_dir.path }}/{{ package_url | basename }}"
    checksum: "{{ package_checksum }}"

# Dependency environment
- name: Create package environment location
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ software_user }}"
    mode: u=rwX,g=rX,o=rX
  loop:
    - "{{ base_path }}"

- name: Install the package environment
  ansible.builtin.command:
    cmd: "/bin/bash {{ temp_dir.path }}/{{ package_url | basename }} -b -s -m -p {{ base_path }}/env"
    creates: "{{ base_path }}/env/envs/spyder-runtime/bin/spyder"

- name: Remove uninstaller template
  ansible.builtin.file:
    path: "{{ base_path }}/env/uninstall-spyder.sh"
    state: absent

- name: Cleanup temporary directory
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent

# Package install by symlinking binary in
- name: Create package install location
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ software_user }}"
    mode: u=rwX,g=rX,o=rX
  loop:
    - "{{ install_path }}/install/bin"

- name: Install the package
  ansible.builtin.file:
    src: "{{ base_path }}/env/envs/spyder-runtime/bin/spyder"
    dest: "{{ install_path }}/install/bin/spyder"
    state: link

# Modules
- name: Install dependency module
  template:
    src: templates/modulefile.j2
    dest: "{{ base_path }}/module.lua"
  vars:
    module:
      module:
        category: "Module"
        vars:
            - module_name: "'{{ package_name }}'"
            - module_version: "'{{ package_version }}'"
            - module_description: "'Dependency environment for {{ package_name }}/{{ package_version }}'"
            - module_help: {"[[ Dependency environment for {{ package_name }}/{{ package_version }}. This module exists as a helper tool, but you only need to load the package's (){{ package_name }}/{{ package_version }}) environment to have access to that. ]]" : str}
        funcs:
          - whatis: ["Name" : str, module_name]
          - whatis: ["Version" : str, module_version]
          - whatis: ["Description" : str, module_description]
          - help: [ module_help ]
      conflicts:
        category: "Conflicts"
        funcs:
            - family: [ "condaenv" : quote ]
            - conflict: [ module_name ]
      requires:
        category: "Requires"
        funcs:
          - depends_on: [ "'micromamba'" ]
      environment:
        category: "Environment"
        cmds:
          - |
            execute {
                cmd = "micromamba activate " .. "{{ base_path }}/env",
                modeA = {"load"}
            }
          - |
            execute {
                cmd = "micromamba deactivate",
                modeA = {"unload"}
            }

- name: Link dependency module - ensure directory is present
  ansible.builtin.file:
    path: "{{ environments_path }}/modulefiles/dependencies/{{ package_name }}/"
    state: directory
    mode: '0755'

- name: Link dependency module - create symlink
  ansible.builtin.file:
    src: "{{ base_path }}/module.lua"
    dest: "{{ environments_path }}/modulefiles/dependencies/{{ package_name }}/{{ package_version }}.lua"
    state: link

- name: Install package module
  template:
    src: templates/modulefile.j2
    dest: "{{ install_path }}/module.lua"
  vars:
    module:
      module:
        category: "Module"
        vars:
          - module_name: "'{{ package_name }}'"
          - module_version: "'{{ package_version }}'"
          - module_description: "'IDE for the Python programming language'"
          - module_help: {"[[ Spyder is an IDE for the Python programming language ]]" : str}
        funcs:
          - whatis: ["Name" : str, module_name]
          - whatis: ["Version" : str, module_version]
          - whatis: ["Description" : str, module_description]
          - help: [ module_help ]
      conflicts:
        category: "Conflicts"
        funcs:
          - conflict: [ module_name ]
      paths:
        category: "Paths"
        funcs:
          - prepend_path: [ "'PATH'" , "'{{ install_path }}/install/bin'" ]

- name: Link package module - ensure directory is present
  ansible.builtin.file:
    path: "{{ local_path }}/modulefiles/{{ package_name }}/"
    state: directory
    mode: '0755'

- name: Link package module - create symlink
  ansible.builtin.file:
    src: "{{ install_path }}/module.lua"
    dest: "{{ local_path }}/modulefiles/{{ package_name }}/{{ package_version }}.lua"
    state: link

