---

name: globalenv
channels:
  - conda-forge
  - minc-forge
  - bioconda
channel_priority: strict
dependencies:
############################
# Basics
############################
  - conda-bash-completion
  - cuda-cudart
  - cuda-version=12
  - cytoscape
  - ffmpeg
  - graphviz
  - gnuplot
  - imagemagick
  - jupyterlab
  - libboost
  - libboost-devel
  - libboost-headers
  - nb_conda_kernels
  - openblas
############################
# PYTHON
############################
# Base
  - python=3.11
  - pip
  - ipython
  - ipykernel
  - ipywidgets
  - biopython
# Spyder dependencies
  - spyder-kernels>=3.1.0,<3.2.0
  - alabaster
  - astroid
  - asyncssh
  - autopep8
  - binaryornot
  - black
  - cattrs
  - cookiecutter
  - diff-match-patch
  - docstring-to-markdown
  - flake8
  - fzf
  - imagesize
  - inflection
  - intervaltree
  - isort
  - jellyfish
  - libspatialindex
  - lsprotocol
  - mccabe
  - nbconvert
  - nbconvert-pandoc
  - numpydoc
  - pickleshare
  - pycodestyle
  - pyconify
  - pydocstyle
  - pyflakes
  - pygithub
  - pylint
  - pylint-venv
  - pyls-spyder
  - pynacl
  - pyqtwebengine
  - python-gssapi
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-ruff
  - python-lsp-server
  - python-lsp-server-base
  - python-slugify
  - pytokens
  - pytoolconfig
  - pyuca
  - qstylizer
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtconsole-base
  - roman-numerals
  - rope
  - rtree
  - ruff
  - snowballstemmer
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - superqt
  - text-unidecode
  - textdistance
  - three-merge
  - ujson
  - watchdog
  - whatthepatch
  - yapf
# Helper packages
  - autoflake
  - bcrypt
  - cffi
  - configparser
  - configupdater
  - icecream
  - memray
  - more-itertools
  - pandoc
  - pdbpp
  - pendulum
  - pipe
  - pybind11
  - pydantic
  - pytest
  - regex
  - rich
  - scalene
  - "setuptools<82" # pkg_resources removed in setuptools>=82. While it is deprecated, it is needed by ITK and qbatch for now.
  - sh
  - six
  - tenacity
  - tqdm
  - ty
  - typer
# Parallel
  - pathos
  - pyinfra
  - qbatch
#  - scoop
  - uproot
# Numerics
  - autograd
  - cvxpy
  - libboost-python
  - libboost-python-devel
  - numba
  - numpy
  - scipy
  - sympy
  - xgboost
# Data frames
  - pandas
  - polars
  - pyarrow
  - pyreadstat
  - sklearn-pandas
  - xarray
# Stats
  - geomstats
  - pymc
  - skglm
  - statsmodels
  - umap-learn
# Image processing
  - imageio
  - itk
  - lapy
  - pillow
  - scikit-fmm
  - simpleitk
  - vtk
# Neuroimaging
  - antspyx
  - bids-validator
  - dcm2bids
  - dcm2niix
  - dcmstack
  - dicomifier
  - dipy
  - mne-bids
  - nibabel
  - nifti-mrs
  - nilearn
  - nitime
  - nipype
  - pybids
# MRI
  - brukerapi
  - sycomore
# Neurophys
  - mne
# Natural language processing
  - lark
  - nltk
# AV processing and data streaming
  - av
  - ffmpeg-python
  - imageio-ffmpeg
  - ipywebrtc
  - opencv
  - moviepy
  - pyaudio
  - python-sounddevice
  - webrtcvad
  - xwebrtc
# Data structures
  - anytree
  - awkward
  - bigtree
  - collections-extended
  - dill
  - h5py
  - jmespath
  - json5
  - jsonschema
  - ml-collections
  - multidict
  - networkx
  - optree
  - pptree
  - toytree
  - treelib
  - pyyaml
  - vector
# Database connections and data organization
  - datalad
  - sqlalchemy
  - psycopg2
  - pyodbc
# ML
  - scikit-image
  - scikit-learn
  - scikit-learn-intelex
  - scikit-multilearn
# Plotting
  - adjusttext
  - bokeh
  - cmaps
  - dash
  - ipycytoscape
  - matplotlib
  - patchworklib
  - plotly
  - plotnine
  - py2cytoscape
  - pypalettes
  - python-graphviz
  - seaborn
# Web scraping
  - beautifulsoup4
  - scrapy
  - selenium
# Web development
  - django
  - fastapi
  - flask
  - pyro4
  - requests
  - streamlit
  - urllib3
  - websockets
  - websocket-client
# Spatial
  - gdal
  - geopandas
  - rasterio
  - shapely
# Genetics
  - gseapy
  - pydeseq2
  - pyscenic
  - scanpy
# GUI
  - pyqt
# Game development
  - pygame
# Physics
  - qutip
# Quantum Computing
  - dwave-system
# External services
  - aiobotocore
  - boto3
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-oauthlib
  - googlemaps
  - mattermostdriver
  - oauthlib
  - qrcode
  - s3fs
  - sentinelhub
# R interface
  - rpy2
  - pyreadr
############################
# R
############################
# Base
  - r-base
  - r-essentials
  - r-recommended
  - r-devtools
  - r-irkernel
  - r-biocmanager
  - radian
# Bioconductor base
  - bioconductor-annotationhub
  - bioconductor-biobase
  - bioconductor-biocviews
  - bioconductor-biocinstaller
# Python interface
  - r-reticulate
# Tidyverse
  - r-tidyverse
  - r-tidymodels
# Helper packages
  - r-argparse
  - r-available
  - r-beepr
  - r-bindr
  - r-config
  - r-configr
  - r-curl
  - r-formula
  - r-gdata
  - r-gert
  - r-glue
  - r-hmisc
  - r-janitor
  - r-logger
  - r-magick
  - r-pak
  - r-pbapply
  - r-rcpp
  - r-recipes
  - r-remotes
  - r-rlang
  - r-svunit
  - r-systemfonts
  - r-tictoc
# Pipelines and parallelization
  - bioconductor-biocparallel
  - r-batchtools
  - r-foreach
  - r-domc
  - r-doparallel
  - r-dosnow
  - r-snowfall
  - r-targets
# Database connections
  - bioconductor-annotationdbi
  - r-dbi
  - r-googlesheets4
  - r-odbc
  - r-rpostgres
  - r-rsqlite
  - r-sparklyr
# Filesystem
  - r-fs
  - r-here
# File formats and I/O
  - r-cairo
  - r-foreign
  - r-jsonlite
  - r-pdftools
  - r-png
  - r-r.matlab
  - r-rcppcnpy
  - r-readxl
  - r-rjson
  - r-rsvg
  - r-svglite
  - r-tiff
  - r-xml2
  - r-yaml
# Table formatting
  - r-flextable
  - r-htmltable
  - r-pillar
  - r-reactable
  - r-xtable
# Data structures, classes, and methods
  - bioconductor-biostrings
  - bioconductor-biocgenerics
  - bioconductor-delayedarray
  - bioconductor-matrixgenerics
  - bioconductor-s4vectors
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - r-arrow
  - r-bigmemory
  - r-blob
  - r-data.table
  - r-data.tree
  - r-dt
  - r-matrix
  - r-igraph
  - r-ontologyindex
  - r-spam
  - r-spam64
  - r-stable
  - r-stringi
  - r-tidytext
  - r-vctrs
  - r-xts
  - r-zoo
# Numerical tools and algorithms
  - bioconductor-biodist
  - bioconductor-bioga
  - bioconductor-bionar
  - bioconductor-iranges
  - bioconductor-rbgl
  - r-abind
  - r-arrayhelpers
  - r-bh
  - r-catboost
  - r-combinat
  - r-fuzzyjoin
  - r-gsl
  - r-matchit
  - r-mboost
  - r-proc
  - r-qlcmatrix
  - r-rann
  - r-reshape
  - r-sparsem
  - r-stars
  - r-tensora
  - r-xgboost
# Signal processing
  - r-gsignal
# Image and shape processing
  - bioconductor-ebimage
  - r-imager
  - r-mmand
  - r-openimager
  - r-spatialtools
  - r-transformr
  - r-tweenr
# Optimization and solvers
  - r-deoptimr
  - r-distances
  - r-fastdummies
  - r-ga
  - r-geepack
  - r-lpsolve
  - r-mcmc
  - r-nloptr
  - r-optimparallel
  - r-optimx
  - r-quadprog
  - r-rcppannoy
  - r-rfast
# Imputation, cleaning, matching, harmonization
  - bioconductor-preprocesscore
  - bioconductor-sva
  - r-bestnormalize
  - r-mice
  - r-missforest
  - r-naniar
  - r-qmap
  - r-rcompanion
  - r-transport
  - r-vim
# Stats, distributions, and testing
  - bioconductor-qvalue
  - r-bigstatsr
  - r-distributional
  - r-emmeans
  - r-hdinterval
  - r-homomorpher
  - r-hotelling
  - r-multcomp
  - r-mvnfast
  - r-mvtnorm
  - r-nortest
  - r-np
  - r-summarytools
  - r-suppdists
# Model fitting: sampling, cross-validation, parameter tuning, performance
  - r-boot
  - r-coda
  - r-cvms
  - r-finetune
  - r-mlr3
  - r-performance
  - r-rsample
  - r-tune
  - r-yardstick
# Modeling
  - r-biglm
  - r-biglasso
  - r-car
  - r-elasticnet
  - r-fitdistrplus
  - r-gamm4
  - r-ggeffects
  - r-glmmtmb
  - r-glmnet
  - r-lme4
  - r-lmertest
  - r-locfit
  - r-matrixmodels
  - r-mgcv
  - r-modelbased
  - r-nlme
  - r-parsnip
  - r-qgam
  - r-quantreg
  - r-rpart
  - r-sandwich
  - r-speedglm
  - r-splines2
  - r-survival
# Clustering
  - r-biclust
  - r-cluster
  - r-clv
  - r-densityclust
  - r-mclust
  - r-rtsne
  - r-snftool
  - r-tsne
  - r-umap
  - r-uwot
# Multivariate
  - r-ddrtree
  - r-fastica
  - r-huge
  - r-ica
  - r-mass
  - r-plsdepot
# Factor analysis
  - r-bootnet
  - r-effsize
  - r-gglasso
  - r-glasso
  - r-grplasso
  - r-grpreg
  - r-lars
  - r-lavaan
  - r-pbkrtest
# Bayesian
  - r-bnlearn
  - r-brms
  - r-posterior
  - r-rstan
  - r-rstanarm
  - r-tidybayes
# ML packages
  - r-caret
  - r-kernlab
  - r-mlr3verse
  - r-nnet
  - r-randomforest
# Plotting - specific types
  - bioconductor-cytomapper
  - bioconductor-geneplotter
  - bioconductor-rcy3
  - r-beeswarm
  - r-calendr
  - r-chromomap
  - r-circlize
  - r-complexupset
  - r-corrplot
  - r-deeptime
  - r-diagrammer
  - r-diagrammersvg
  - r-effects
  - r-factoextra
  - r-flexplot
  - r-gplots
  - r-gridbase
  - r-interactions
  - r-jskm
  - r-jtools
  - r-mlr3viz
  - r-pheatmap
  - r-plotrix
  - r-protviz
  - r-qgraph
  - r-rgl
  - r-semplot
  - r-sjplot
  - r-superheat
  - r-tidyplots
  - r-upsetr
  - r-vcd
  - r-vipor
  - r-visdat
  - r-visnetwork
  - r-vistime
# Plotting - ggplot extensions
  - r-cowplot
  - r-cropcircles
  - r-directlabels
  - r-dotwhisker
  - r-ezplot
  - r-geofacet
  - r-geomtextpath
  - r-ggalign
  - r-ggalluvial
  - r-ggally
  - r-ggalt
  - r-gganatogram
  - r-ggbeeswarm
  - r-ggbiplot
  - r-ggblanket
  - r-ggblend
  - r-ggbreak
  - r-ggbump
  - r-ggcharts
  - r-ggcorrplot
  - r-ggcorset
  - r-ggcoverage
  - r-ggdag
  - r-ggdark
  - r-ggdendro
  - r-ggdensity
  - r-ggdist
  - r-ggeasy
  - r-ggextra
  - r-ggfittext
  - r-ggflowchart
  - r-ggfocus
  - r-ggforce
  - r-ggformula
  - r-ggfortify
  - r-ggfun
  - r-ggfx
  - r-gggenes
  - r-gggenomes
  - r-gggrid
  - r-ggh4x
  - r-gghalves
  - r-gghighlight
  - r-gghoriplot
  - r-ggimage
  - r-gginnards
  - r-ggmap
  - r-ggmice
  - r-ggmosaic
  - r-ggmuller
  - r-ggmulti
  - r-ggnetwork
  - r-ggnewscale
  - r-ggpackets
  - r-ggpage
  - r-ggparallel
  - r-ggparty
  - r-ggpattern
  - r-ggplate
  - r-ggplotify
  - r-ggpmisc
  - r-ggpointdensity
  - r-ggpointless
  - r-ggpol
  - r-ggpolypath
  - r-ggpp
  - r-ggpubr
  - r-ggpval
  - r-ggragged
  - r-ggrandomforests
  - r-ggraph
  - r-ggrastr
  - r-ggrepel
  - r-ggresidpanel
  - r-ggridges
  - r-ggsci
  - r-ggseqlogo
  - r-ggseqplot
  - r-ggside
  - r-ggsignif
  - r-ggspatial
  - r-ggspectra
  - r-ggstance
  - r-ggstar
  - r-ggstats
  - r-ggstatsplot
  - r-ggsurvfit
  - r-ggtangle
  - r-ggtern
  - r-ggtext
  - r-ggtime
  - r-ggthemes
  - r-ggupset
  - r-ggvenn
  - r-ggvenndiagram
  - r-ggwordcloud
  - r-grafify
  - r-hrbrthemes
  - r-lemon
  - r-legendry
  - r-metr
  - r-patchwork
  - r-plotroc
  - r-qqplotr
  - r-rayshader
  - r-scattermore
  - r-see
  - r-survminer
  - r-treeheatr
  - r-treemapify
  - r-waffle
  - r-waterfalls
# Plotting - colours, layouts, and scales
  - r-colorblindness
  - r-cols4all
  - r-crayon
  - r-egg
  - r-gameofthrones
  - r-ggdark
  - r-ggokabeito
  - r-ggprism
  - r-ggsn
  - r-graphlayouts
  - r-gtable
  - r-harrypotter
  - r-jcolors
  - r-metbrewer
  - r-paletteer
  - r-pals
  - r-polychrome
  - r-rcartocolor
  - r-rcolorbrewer
  - r-scales
  - r-scico
  - r-thematic
  - r-trekcolors
  - r-viridis
  - r-wesanderson
# Plotting - interactive and animations
  - r-esquisse
  - r-gganimate
  - r-ggedit
  - r-ggiraph
  - r-ggiraphextra
  - r-ggvis
  - r-plotly
  - r-shiny
# Domain specific
  - bioconductor-annotate
  - bioconductor-biocartaimage
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-customcmpdb
  - bioconductor-drugtargetinteractions
  - bioconductor-edger
  - bioconductor-genefilter
  - bioconductor-genomeinfodbdata
  - bioconductor-hpaanalyze
  - bioconductor-hpar
  - bioconductor-kebabs
  - bioconductor-keggrest
  - bioconductor-limma
  - bioconductor-mast
  - bioconductor-monocle
  - bioconductor-orthogene
  - bioconductor-piano
  - bioconductor-pharmacogx
  - bioconductor-reactomepa
  - bioconductor-rots
  - bioconductor-rwikipathways
  - bioconductor-stringdb
  - bioconductor-tenxplore
  - bioconductor-variancepartition
  - r-av
  - r-cvtools
  - r-envstats
  - r-epi
  - r-fields
  - r-httr
  - r-landscapemetrics
  - r-maps
  - r-maptools
  - r-oce
  - r-phylogram
  - r-psych
  - r-rideogram
#  - r-rminc
  - r-rselenium
  - r-quantmod
  - r-rstoolbox
  - r-satellite
  - r-seurat
  - r-seuratobject
  - r-sf
  - r-signac
  - r-sp
  - r-startr
  - r-suncalc
  - r-terra
#  - r-tmod
  - r-transformer
  - r-transphylo
  - r-vegan
# Datasets
  - bioconductor-bioimagedbs
  - bioconductor-biomart
  - bioconductor-biomartgogenesets
  - bioconductor-chemminedrugs
  - bioconductor-do.db
  - bioconductor-go.db
  - bioconductor-hdo.db
  - bioconductor-jaspar2024
  - bioconductor-kegg.db
  - bioconductor-msigdb
  - bioconductor-org.at.tair.db
  - bioconductor-org.dm.eg.db
  - bioconductor-org.dr.eg.db
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-org.rn.eg.db
  - bioconductor-org.sc.sgd.db
  - bioconductor-reactome.db
  - r-cancensus
  - r-cansim
  - r-dslabs
  - r-fivethirtyeight
  - r-gapminder
  - r-lahman
  - r-metadat

