---

name: globalenv
python_packages:
  trusted:
    source:
      pypi:
      # Numerics
        - jax
        - jaxlib
      # Neuroimaging
        - abagen
        - allensdk
        - asltk
        - brainstat
        - neurosynth
        - neuroquery
        - nimagen
        - nimare
        - pcntoolkit
        - pyminc
      # MRI
        - brkraw
        - brkraw-dti
        - brkraw-mrs
        - brkraw-sordino
        - brkraw-viewer
        - cmrsim
      # Stats
        - group-lasso
        - lassonet
        - opnmf
      # AV
        - aiortc
        - streamlit-webrtc
      # Data mining
        - pubget
      # Visualization
        - lets-plot
        - plotnine3d
      # GUI
        - pyqt5-tools
      # External services
        - mattermost
        - mattermost-notify
        - pydo
      # Domain specific
        - particle
      github:
        - "noxtoby/awkde": awkde
        - "ucl-pond/kde_ebm": kde_ebm
        - "ucl-pond/pySuStaIn": pySuStaIn
  unverified:
    source:
      pypi:
        - jaxkuramoto
        - kuramoto
        - kuramoto-chimera
  deprecated:
    source:
      pypi:
        - snap-stanford
      pypi_no_deps:
      # Image processing
        - itk-vtkglue

r_packages:
  trusted:
    source:
      cran:
      # Development
        - CodeDepends
        - functiondepends
        - funviewR
        - pkgdepR
        - pkgnet
      # Numerics
        - AMCMC
        - fmcmc
        - RcppHungarian
        - sparsegl
      # Image processing
        - geomorph
        - ICvectorfields
        - morph
      # Distributed data
        - distcomp
      # Processing and imputation
        - EpiEstim
        - imputeTS
      # Stats distributions and testing
        - ppsr
        - stability
      # Model fitting and optimization
        - calibrar
        - fitlandr
        - lglasso
        - LassoNet
        - moderndive
        - pso
        - rBayesianOptimization
      # Imaging
        - brainGraph
        - fmri
        - fsbrain
        - fslr
        - neuroim2
        - oro.dicom
        - oro.nifti
        - RNifti
      # Topological data analysis
        - inphr
        - phutil
        - rgph
        - ripserr
        - tdarec
        - TDAstats
        - tdaunif
      # Plotting - specific types
        - autograph
        - easyalluvial
        - effectplots
        - likert
        - lindia
        - metrica
        - parttree
        - plotthis
        - qbinplots
        - rfviz
        - smplot2
        - splineplot
        - swimplot
        - vismi
      # Plotting - ggplot extensions
        - biscale
        - canadamaps
        - canadianmaps
        - edgebundle
        - flowmapper
        - FunnelPlotR
        - gaussplotR
        - gg1d
        - ggalignment
        - ggarchery
        - ggarrow
        - ggautomap
        - ggbrace
        - ggbrain
        - ggbrick
        - ggchord
        - ggcompare
        - ggcorrheatmap
        - ggdaynight
        - ggdiagram
        - ggdibbler
        - ggdiceplot
        - ggDNAvis
        - ggDoE
        - ggDoubleHeat
        - ggEDA
        - ggfacto
        - ggfields
        - ggfixest
        - ggfoundry
        - gggda
        - ggguides
        - gghexsize
        - gghourglass
        - ggimg
        - ggincerta
        - ggip
        - ggisotonic
        - gglinedensity
        - gglm
        - gglogger
        - gglorenz
        - gglyph
        - ggmapcn
        - ggmapinset
        - ggmugs
        - ggnuplot
        - ggOceanMaps
        - ggordiplots
        - ggpath
        - ggpca
        - ggpcp
        - ggpedigree
        - ggperiodic
        - ggpicrust2
        - ggpolar
        - ggQQunif
        - ggquiver
        - ggrain
        - ggrecipes
        - ggredist
        - ggreveal
        - ggrounded
        - ggsankeyfier
        - ggScatRidges
        - ggsced
        - ggseg
        - ggsegmentedtotalbar
        - ggsem
        - ggshadow
        - ggskewboxplots
        - ggsky
        - ggsmc
        - ggspark
        - ggstackplot
        - ggsurveillance
        - ggswissmaps
        - ggtaxplot
        - ggtibble
        - ggtikz
        - ggtrace
        - ggtranslate
        - ggtreebar
        - ggtrendline
        - ggtricks
        - ggvegan
        - ggvfields
        - ggx
        - gratia
        - halfmoon
        - insetplot
        - layer
        - mapcan
        - mapSpain
        - oblicubes
        - ozmaps
        - plotcli
        - scatterbar
        - sugarbag
        - sugarglider
        - sugrrants
        - superb
        - tidyterra
        - WVPlots
      # Plotting - colours, layouts, and scales
        - afcharts
        - amerika
        - DOYPAColors
        - figpatch
        - flexoki
        - GGenemy
        - gghdx
        - gglgbtq
        - ggRtsy
        - ggtea
        - ggview
        - ggwidth
        - jumble
        - MexBrewer
        - monochromeR
        - NatParksPalettes
        - nord
        - okcolors
        - onsvplot
        - pagenum
        - poisonfrogs
        - PrettyCols
        - rbranding
        - Rdune
        - roughnet
        - roughsf
        - savonliquide
        - stevethemes
        - tayloRswift
        - tgamtheme
        - tinythemes
        - tricolore
        - unhcrthemes
        - unicol
        - unikn
        - vangogh
      # Plotting - interactive
        - blockr.ggplot
        - camcorder
        - ggfigdone
        - ivolcano
      # Domain specific
        - cv
        - hdcuremodels
        - landsat
        - qrencoder
        - rphylopic
        - RRmorph
        - RRphylo
        - tongfen
        - upstartr
        - vitae
      # Data
        - bcdata
        - cancensus
        - cansim
        - causaldata
        - ces
        - cmhc
        - opendatatoronto
        - psymetadata
        - tidyhydat
        - VancouvR
      bioconductor:
        - Rgraphviz
        - ggkegg
      github:
      # Neuroimaging
        - "andy1764/CovBat_Harmonization/R": CovBat
        - "ANTsX/ANTsR": ANTsR
        - "bidsconvertr/bidsconvertr": bidsconvertr
        - "jfortin1/neuroCombatData": neuroCombatData
        - "jfortin1/neuroCombat_Rpackage": neuroCombat_Rpackage
        - "Mouse-Imaging-Centre/RMINC@develop": RMINC
        - "Mouse-Imaging-Centre/MRIcrotome": MRIcrotome
        - "SimpleITK/SimpleITKRInstaller": SimpleITK
      # Stats
        - "yohanyee/normtools": normtools
  unverified:
    source:
      github:
      # Neuroimaging
        - "muschellij2/extrantsr": extrantsr
      # Stats and data structures
        - "DataSlingers/ExclusiveLasso": ExclusiveLasso
        - "dhruba018/DMTL": DMTL
        - "hyunjimoon/SBC": SBC
        - "r-lib/rray": rray
        - "StoreyLab/biobroom": biobroom
      # Domain specific
        - "msberends/AMR": AMR
        - "peekxc/simplextree": simplextree
        - "tdaverse/interplex": interplex
      # External
        - "GreenGrassBlueOcean/MattermostR": MattermostR
      # Plotting
        - "AakaashRao/starbility": starbility
        - "Ather-Energy/ggTimeSeries": ggTimeSeries
        - "benyamindsmith/mapBliss": mapBliss
        - "benyamindsmith/starBliss": starBliss
        - "BjnNowak/bertin": bertin
        - "briatte/ggnet": ggnet
        - "bwanniarachchige2/ggtwotone": ggtwotone
        - "coolbutuseless/ggsvg": ggsvg
        - "davidsjoberg/ggsankey": ggsankey
        - "davidsjoberg/ggstream": ggstream
        - "diegovalle/mxmaps": mxmaps
        - "dill/emoGG": emoGG
        - "dxsbiocc/ggideogram": ggideogram
        - "dzhang32/ggtranscript": ggtranscript
        - "eliocamp/ggpercentogram": ggpercentogram
        - "ellisp/ggseas/pkg": ggseas
        - "emilhvitfeldt/ggrandom": ggrandom
        - "EvaMaeRey/ggcalendar": ggcalendar
        - "EvaMaeRey/ggols": ggols
        - "EvaMaeRey/ggstamp": ggstamp
        - "gadenbuie/ggweekly": ggweekly
        - "garretrc/ggvoronoi": ggvoronoi
        - "gnoblet/ggbranding": ggbrandin
        - "giocomai/ganttrify": ganttrify
        - "hrbrmstr/ggcounty": ggcounty
        - "hrbrmstr/ggeconodist": ggeconodist
        - "hrbrmstr/ggsolar": ggsolar
        - "hughjonesd/ggmagnify": ggmagnify
        - "Hy4m/ggvwline": ggvwline
        - "i2z1/ggonion": ggonion
        - "inbo/effectclass": effectclass
        - "jared-fowler/prettyglm": prettyglm
        - "jasonwong-lab/gghic": gghic
        - "Jiawang1209/ggNetView": ggNetView
        - "jimjam-slam/ggflags": ggflags
        - "jhrcook/ggasym": ggasym
        - "jfjelstul/eumaps": eumaps
        - "junjunlab/jjAnno": jjAnno
        - "kenithgrey/ggQC": ggQC
        - "leonardojo/ggPlantmap": ggPlantmap
        - "liamgilbey/ggwaffle": ggwaffle
        - "MarcellGranat/ggProfessional": ggProfessional
        - "MattCowgill/ggdirectlabel": ggdirectlabel
        - "mrjoh3/ggtrack": ggtrack
        - "nacnudus/ggbillboard": ggbillboard
        - "nacnudus/ggstraw": ggstraw
        - "nevrome/ggpointgrid": ggpointgrid
        - "nsgrantham/ggbraid": ggbraid
        - "openpharma/visR": visR
        - "paezha/truchet": truchet
        - "R-CoderDotCom/ggcats": ggcats
        - "r-link/corrmorant": corrmorant
        - "ricardo-bion/ggradar": ggradar
        - "rkabacoff/ggpie": ggpie
        - "Sayani07/gghdr": gghdr
        - "sctyner/geomnet": geomnet
        - "sharlagelfand/ggkeyboard": ggkeyboard
        - "teunbrand/ggplateplot": ggplateplot
        - "tgerke/ggconsort": ggconsort
        - "tdaverse/ggtda": ggtda
        - "UrbanInstitute/urbnmapr": urbnmapr
        - "yanpd01/ggsector": ggsector
        - "yutannihilation/ggsflabel": ggsflabel
        - "zmeers/ggparliament": ggparliament
      # Plotting - color maps, layouts, scales, etc
        - "ashgreat/roughVizR": roughVizR
        - "bbc/bbplot": bbplot
        - "BlakeRMills/MoMAColors": MoMAColors
        - "clauswilke/ggtextures": ggtextures
        - "coolbutuseless/facetious": facetious
        - "datacamp/ggdc": ggdc
        - "delabj/ggCyberPunk": ggCyberPunk
        - "dracula/dRacula": dRacula
        - "EdwinTh/dutchmasters": dutchmasters
        - "ekholme/blueycolors": blueycolors
        - "friendly/ggCheysson": ggCheysson
        - "gadenbuie/ggpomological": ggpomological
        - "Greater-London-Authority/gglaplot": gglaplot
        - "jbgb13/peRReo": peRReo
        - "Jiawang1209/ggSketch": ggSketch
        - "johannesbjork/LaCroixColoR": LaCroixColoR
        - "johnmackintosh/rockthemes": rockthemes
        - "junqueiragaabi/ButterflyColors": ButterflyColors
        - "kaizadp/soilpalettes": soilpalettes
        - "MatthewBJane/ThemePark": ThemePark
        - "Mikata-Project/ggthemr": ggthemr
        - "mjskay/ggblend": ggblend
        - "olihawkins/pilot": pilot
        - "R-CoderDotCom/cyberpunk": cyberpunk
        - "RestlessTail/ggGenshin": ggGenshin
        - "ricardo-bion/ggtech": ggtech
        - "Ryo-N7/tvthemes": tvthemes
        - "sharlagelfand/ggcute": ggcute
        - "teunbrand/ggchromatic": ggchromatic
        - "thomas-neitmann/mdthemes": mdthemes
        - "UrbanInstitute/urbnthemes": urbnthemes
        - "xvrdm/ggrough": ggrough
        - "xvzftube/darknerdthemes": darknerdthemes
        - "yjunechoe/ggcolormeter": ggcolormeter
      # Plotting - 3D
        - "coolbutuseless/cryogenic": cryogenic
        - "coolbutuseless/devout": devout
        - "coolbutuseless/devoutrgl": devoutrgl
        - "coolbutuseless/snowcrash": snowcrash
        - "coolbutuseless/ggreverse": ggreverse
        - "coolbutuseless/ggrgl": ggrgl
        - "coolbutuseless/ggthreed":  ggthreed
        - "coolbutuseless/threed": threed
        - "coolbutuseless/triangular": triangular
      # Plotting - interactive
        - "AliciaSchep/gglabeller": gglabeller
        - "MattCowgill/ggannotate": ggannotate
        - "Roche/ggtips": ggtips
        - "terrytangyuan/autoplotly": autoplotly
      # Data
        - "hodgettsp/cesR": cesR
        - "mountainmath/canbank": canbank
        - "mountainmath/CanCovidData": CanCovidData
        - "mountainmath/canpumf": canpumf
        - "mountainmath/statcanXtabs": statcanXtabs
        - "paleolimbot/rcanvec": rcanvec
        - "ropensci/weathercan": weathercan
      gitlab:
        - "hrbrmstr/ggchicklet": ggchicklet
        - "medbio/disgenet2r": disgenet2r
  deprecated:
    source:
      cran:
        - ggESDA
        - neuroimaGene
        - Rgnuplot
        - trafo
