--- # av

##################################################################################
# AV processing and analysis environment
##################################################################################

####################################
# Satisfy dependencies
####################################

- name: "Run dependency tasks: ensure micromamba binary is present"
  ansible.builtin.include_tasks: micromamba.yml

####################################
# Get variables and set task variables/paths
####################################

# Get vars from roles' vars/ directory
- name: Get package/environment information
  ansible.builtin.set_fact:
    condaenv: "{{ av.condaenv }}"

# Set task vars
- name: Set task variables
  ansible.builtin.set_fact:
    environment_name: "{{ condaenv.info.name }}"
    environment_version: "{{ condaenv.info.version }}"
    environment_type: "{{ condaenv.info.type }}"

# Get environment path
- name: Defining environment path
  ansible.builtin.set_fact:
    base_path: "{{ environments_path }}/{{ environment_type }}/{{ environment_name }}/{{ environment_version }}"
    thisenv_path: "{{ environments_path }}/{{ environment_type }}/{{ environment_name }}/{{ environment_version }}/env"

- name: Defining a temporary log file for environment creation
  ansible.builtin.set_fact:
    create_env_tmpfile: "{{ base_path }}/mamba_create_env.log"

####################################
# Setup install directories and copy specs
####################################

# Setup initial directories
- name: Create required directories
  become_user: root
  ansible.builtin.file:
    path: "{{ base_path }}"
    state: directory
    owner: "{{ condaenv.owner.user }}"
    group: "{{ condaenv.owner.group }}"
    mode: u=rwx,g=rx,o=rx

# Copy environment file
- name: Copying environment file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ base_path }}/"
    owner: "{{ condaenv.owner.user }}"
    group: "{{ condaenv.owner.group }}"
    mode: u=rw,g=r,o=r
  loop:
    - "files/{{ condaenv.specs.conda }}"
    - "files/{{ condaenv.specs.other }}"

####################################
# Create environment
####################################

- name: Check micromamba info
  ansible.builtin.shell:
    cmd: |
      export MAMBA_ROOT_PREFIX="{{ root_prefix }}"
      source "{{ root_prefix }}/etc/profile.d/mamba.sh"
      mamba info
    executable: /bin/bash
  register: debug_out

- name: Print micromamba info
  ansible.builtin.debug:
    var: debug_out.stdout_lines

# Create Conda environment
- name: Create environment
  ansible.builtin.shell:
    cmd: >
      export MAMBA_ROOT_PREFIX="{{ root_prefix }}"
      && source "{{ root_prefix }}/etc/profile.d/mamba.sh"
      && umask 022
      && /usr/bin/time -v mamba -vvv create --quiet --yes -p "{{ thisenv_path }}" -f "{{ base_path }}/{{ condaenv.specs.conda }}" 2>&1 | tee "{{ create_env_tmpfile }}"
    executable: /bin/bash
  args:
    creates: "{{ thisenv_path }}"
  tags:
    - conda
    - trusted

####################################
# Prepare for installation of non-conda packages
####################################

# Get non-conda packages
- name: Load extra package list
  ansible.builtin.include_vars:
    file: "{{ base_path }}/{{ condaenv.specs.other }}"

# Set R version for library path definition
- name: Find R version
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "cat(paste(R.version$major, strsplit(R.version$minor, \"\\\\\\.\")[[1]][[1]], sep=\".\"))"
  register: r_version_call

- name: Set R version variable
  ansible.builtin.set_fact:
    r_version: "{{ r_version_call.stdout }}"

# Create shared R library
- name: Create shared R library
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ condaenv.owner.user }}"
    group: "{{ condaenv.owner.group }}"
    mode: u=rwx,g=rx,o=rx
  loop:
    - "{{ share_path }}/R/library/{{ r_version }}"

####################################
# Install extra trusted packages
####################################

# Install Python packages - trusted - PyPI
- name: Install trusted Python packages via PyPI
  ansible.builtin.pip:
    name: "{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
  loop: "{{ python_packages.trusted.source.pypi }}"
  when: python_packages.trusted.source.pypi is defined
  tags:
    - pypi
    - trusted

# Install Python packages - trusted - PyPI without deps
- name: Install trusted Python packages via PyPI (no dependencies)
  ansible.builtin.pip:
    name: "{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
    extra_args: "--no-deps"
  loop: "{{ python_packages.trusted.source.pypi_no_deps }}"
  when: python_packages.trusted.source.pypi_no_deps is defined
  tags:
    - pypi
    - trusted

# Install Python packages - trusted - GitHub
- name: Install trusted Python packages via GitHub
  ansible.builtin.pip:
    name: "git+https://github.com/{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
  loop: "{{ python_packages.trusted.source.github }}"
  when: python_packages.trusted.source.github is defined
  tags:
    - github
    - trusted

# Install Python packages - trusted - GitHub without deps
- name: Install trusted Python packages via GitHub (no dependencies)
  ansible.builtin.pip:
    name: "git+https://github.com/{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
    extra_args: "--no-deps"
  loop: "{{ python_packages.trusted.source.github_no_deps }}"
  when: python_packages.trusted.source.github_no_deps is defined
  tags:
    - github
    - trusted

# Install R packages - trusted - CRAN
- name: Install trusted R CRAN packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { install.packages(\"{{ item if item is string else (item.keys() | first) }}\", repos=c(\"https://cran.rstudio.com/\")); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.trusted.source.cran }}"
  when: r_packages.trusted.source.cran is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - cran
    - trusted

# Install R packages - trusted - BioConductor
- name: Install trusted Bioconductor R packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { BiocManager::install(\"{{ item if item is string else (item.keys() | first) }}\"); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.trusted.source.bioconductor }}"
  when: r_packages.trusted.source.bioconductor is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - bioconductor
    - trusted

# Install R packages - trusted - GitHub
- name: Install trusted GitHub R packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { devtools::install_github(\"{{ item if item is string else (item.keys() | first) }}\"); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.trusted.source.github }}"
  when: r_packages.trusted.source.github is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - github
    - trusted

# Install R packages - trusted - GitLab
- name: Install trusted GitLab R packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { devtools::install_gitlab(\"{{ item if item is string else (item.keys() | first) }}\"); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.trusted.source.gitlab }}"
  when: r_packages.trusted.source.gitlab is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - gitlab
    - trusted

# ####################################
# # Install extra unverified packages
# ####################################

# Install Python packages - unverified - PyPI
- name: Install unverified Python packages via PyPI
  ansible.builtin.pip:
    name: "{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
  loop: "{{ python_packages.unverified.source.pypi }}"
  when: python_packages.unverified.source.pypi is defined
  tags:
    - pypi
    - unverified
    - never

# Install Python packages - unverified - PyPI without deps
- name: Install unverified Python packages via PyPI (no dependencies)
  ansible.builtin.pip:
    name: "{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
    extra_args: "--no-deps"
  loop: "{{ python_packages.unverified.source.pypi_no_deps }}"
  when: python_packages.unverified.source.pypi_no_deps is defined
  tags:
    - pypi
    - unverified
    - never

# Install Python packages - unverified - GitHub
- name: Install unverified Python packages via GitHub
  ansible.builtin.pip:
    name: "git+https://github.com/{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
  loop: "{{ python_packages.unverified.source.github }}"
  when: python_packages.unverified.source.github is defined
  tags:
    - github
    - unverified
    - never

# Install Python packages - unverified - GitHub without deps
- name: Install unverified Python packages via GitHub (no dependencies)
  ansible.builtin.pip:
    name: "git+https://github.com/{{ item if item is string else (item.keys() | first) }}"
    state: present
    executable: "{{ thisenv_path }}/bin/pip"
    extra_args: "--no-deps"
  loop: "{{ python_packages.unverified.source.github_no_deps }}"
  when: python_packages.unverified.source.github_no_deps is defined
  tags:
    - github
    - unverified
    - never

# Install R packages - unverified - CRAN
- name: Install unverified R CRAN packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { install.packages(\"{{ item if item is string else (item.keys() | first) }}\", repos=c(\"https://cran.rstudio.com/\")); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.unverified.source.cran }}"
  when: r_packages.unverified.source.cran is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - cran
    - unverified
    - never

# Install R packages - unverified - BioConductor
- name: Install unverified Bioconductor R packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { BiocManager::install(\"{{ item if item is string else (item.keys() | first) }}\"); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.unverified.source.bioconductor }}"
  when: r_packages.unverified.source.bioconductor is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - bioconductor
    - unverified
    - never

# Install R packages - unverified - GitHub
- name: Install unverified GitHub R packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { devtools::install_github(\"{{ item if item is string else (item.keys() | first) }}\"); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.unverified.source.github }}"
  when: r_packages.unverified.source.github is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - github
    - unverified
    - never

# Install R packages - unverified - GitLab
- name: Install unverified GitLab R packages
  ansible.builtin.command:
    argv:
      - "{{ thisenv_path }}/bin/Rscript"
      - --vanilla
      - -e
      - "if (! (\"{{ item if item is string else (item.values() | first) }}\" %in% installed.packages()[,\"Package\"])) { devtools::install_gitlab(\"{{ item if item is string else (item.keys() | first) }}\"); cat(\"Package installed\"); quit(status = 0, save = \"no\") } else { cat(\"Package exists\"); quit(status = 0, save = \"no\") }"
  environment: "{{ R_pkg_build_vars }}"
  loop: "{{ r_packages.unverified.source.gitlab }}"
  when: r_packages.unverified.source.gitlab is defined
  register: rscript_result
  changed_when: "'Package installed' in rscript_result.stdout"
  failed_when: rscript_result.rc >= 1
  tags:
    - gitlab
    - unverified
    - never


####################################
# Cleanup
####################################

- name: Cleanup temporary file
  ansible.builtin.file:
    path: "{{ create_env_tmpfile }}"
    state: absent

####################################
# Install and link module
####################################

# Install module
- name: Install module
  ansible.builtin.template:
    src: templates/modulefile.j2
    dest: "{{ base_path }}/module.lua"
    owner: "{{ condaenv.owner.user }}"
    group: "{{ condaenv.owner.group }}"
    mode: u=rw,g=r,o=r
  vars:
    module:
      module:
        category: "Module"
        vars:
          - module_name: "'{{ condaenv.info.name }}'"
          - module_version: "'{{ condaenv.info.version }}'"
          - module_description: "'{{ condaenv.module.description }}'"
          - module_help: "'{{ condaenv.module.help }}'"
        funcs:
          - whatis: [ module_description ]
          - help: [ module_help ]
      conflicts:
        category: "Conflicts"
        funcs:
            - family: [ "condaenv" : quote ]
            - conflict: [ module_name ]
      requires:
        category: "Requires"
        funcs:
          - depends_on: [ "'micromamba'" ]
      paths:
        category: "Paths"
        funcs:
          - prepend_path: [ "'LD_LIBRARY_PATH'" , "'{{ thisenv_path }}/lib/R/lib'" ]
          - prepend_path: [ "'R_LIBS_SITE'" , "'{{ thisenv_path }}/lib/R/library:{{ share_path }}/R/library/{{ r_version }}'" ]
      environment:
        category: "Environment"
        funcs:
          - pushenv: [ "'RSTUDIO_WHICH_R'" , "'{{ thisenv_path }}/bin/R'" ]
        cmds:
          - |
            execute {
                cmd = "micromamba activate " .. "{{ thisenv_path }}",
                modeA = {"load"}
            }
          - |
            execute {
                cmd = "micromamba deactivate",
                modeA = {"unload"}
            }


- name: Link module - ensure directory is present
  ansible.builtin.file:
    path: "{{ environments_path }}/modulefiles/{{ environment_type }}/{{ environment_name }}/"
    state: directory
    owner: "{{ condaenv.owner.user }}"
    group: "{{ condaenv.owner.group }}"
    mode: u=rwX,g=rX,o=rX

- name: Link module - create symlink
  ansible.builtin.file:
    src: "{{ base_path }}/module.lua"
    dest: "{{ environments_path }}/modulefiles/{{ environment_type }}/{{ environment_name }}/{{ environment_version }}.lua"
    owner: "{{ condaenv.owner.user }}"
    group: "{{ condaenv.owner.group }}"
    state: link
