---

- import_tasks: micromamba.yml
  tags:
    - "environment"
    - "micromamba"

- import_tasks: globalenv.yml
  tags:
    - "environment"
    - "global"
    - "globalenv"

- import_tasks: av.yml
  tags:
    - "environment"
    - "standard"
    - "av"

- import_tasks: itksnap-dls.yml
  tags:
    - "environment"
    - "dependencies"
    - "itksnap-dls"


