---

# Platform name
platform_name: "PLATFORM"

# Platform paths
environments_path: /opt/environments
local_path: /opt/local
pipelines_path: /opt/pipelines
quarantine_path: /opt/quarantine
share_path: /opt/share
site_path: /opt/site
cvmfs_path: /cvmfs

# Standard paths
storage_common: /platform/common
storage_data: /platform/data
storage_home: /home
storage_projects: /platform/projects
storage_repos: /platform/repos

# Users
admin_user: admin
software_user: software
cvmfs_user: cvmfs

# Environment variables
environment:
  APPTAINER_TMPDIR: /scratch
