---

- import_tasks: packagemanager.yml
  tags:
    - "provisioning"
    - "packagemanager"

- import_tasks: packages.yml
  tags:
    - "provisioning"
    - "packages"

- import_tasks: users.yml
  tags:
    - "provisioning"
    - "users"

- import_tasks: platform_profile.yml
  tags:
    - "provisioning"
    - "platform_profile"





