--- # Install micromamba

# Load micromamba vars
- name: Load vars for micromamba install
  ansible.builtin.include_vars:
    file: ../environments/vars/main.yml

# Get vars
- name: Get/set variables from vars/ directory
  ansible.builtin.set_fact:
    package_name: "{{ micromamba.package.name }}"
    package_version: "{{ micromamba.package.version }}"
    base_path: "{{ share_path }}/software/{{ micromamba.package.name }}/{{ micromamba.package.version }}"

# Setup initial directories
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ software_user }}"
    mode: u=rwX,g=rX,o=rX
  loop:
    - "{{ base_path }}/install/bin"

- name: Check vars for micromamba install
  ansible.builtin.debug:
    msg: "Root prefix: {{ root_prefix }}, auto activate?: {{ root_prefix_condarc.auto_activate_base }}"

# Install micromamba using mambaorg.micromamba role
- name: Install micromamba
  include_role:
    name: mambaorg.micromamba
  vars:
    arch: "{{ micromamba.package.arch }}" # Overrides default arch roles/mambaorg.micromamba/defaults/main.yml
    version: "{{ micromamba.package.version }}" # Overrides default version roles/mambaorg.micromamba/defaults/main.yml
    dest: "{{ base_path }}/install/bin/micromamba" # Overrides default destination roles/mambaorg.micromamba/defaults/main.yml

- name: Install module
  template:
    src: templates/modulefile.j2
    dest: "{{ base_path }}/module.lua"
  vars:
    module:
      module:
        category: "Module"
        vars:
          - module_name: "'{{ package_name }}'"
          - module_version: "'{{ package_version }}'"
          - module_description: "'micromamba is a standalone replacement for conda/mamba'"
          - module_help: {"[[ micromamba can be used to work with conda environments ]]" : str}
        funcs:
          - whatis: ["Name" : str, module_name]
          - whatis: ["Version" : str, module_version]
          - whatis: ["Description" : str, module_description]
          - help: [ module_help ]
      conflicts:
        category: "Conflicts"
        funcs:
          - family: [ "conda" : quote ]
          - conflict: [ module_name ]
      environment:
        funcs:
          - pushenv: [ "'MAMBA_ROOT_PREFIX'" , "'{{ root_prefix }}'" ]
      paths:
        category: "Paths"
        vars:
        funcs:
          - prepend_path: [ "'PATH'" , "'{{ base_path }}/install/bin'" ]
      conda:
        category: "Conda"
        vars:
          - mamba_hook_call: '"\"$(micromamba shell hook --shell " .. myShellName() .. ")\""'
        cmds:
          - |
            execute {
              cmd = "eval " .. mamba_hook_call,
              modeA = {"load"}
            }
          - |
            execute {
              cmd = "unset micromamba",
              modeA = {"unload"}
            }


- name: Link module - ensure directory is present
  ansible.builtin.file:
    path: "{{ share_path }}/modulefiles/{{ package_name }}/"
    state: directory
    mode: '0755'

- name: Link module - create symlink
  ansible.builtin.file:
    src: "{{ base_path }}/module.lua"
    dest: "{{ share_path }}/modulefiles/{{ package_name }}/{{ package_version }}.lua"
    state: link

# Change root prefix ownership back to software user
- name: Change ownership of root prefix directory
  ansible.builtin.file:
    path: "{{ root_prefix }}"
    state: directory
    owner: "{{ software_user }}"
    group: "{{ software_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

# Change root prefix ownership back to software user
- name: Change ownership of software directory
  ansible.builtin.file:
    path: "{{ share_path }}/software/{{ package_name }}"
    state: directory
    owner: "{{ software_user }}"
    group: "{{ software_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes

# Change root prefix ownership back to software user
- name: Change ownership of module directory
  ansible.builtin.file:
    path: "{{ share_path }}/modulefiles/{{ package_name }}"
    state: directory
    owner: "{{ software_user }}"
    group: "{{ software_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
