--- # Create directories

# Setup initial directories
- name: Create required directories for software
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ software_user }}"
    group: "{{ software_user }}"
    mode: u=rwx,g=rx,o=rx
  loop:
    - "{{ environments_path }}/global"
    - "{{ environments_path }}/standard"
    - "{{ environments_path }}/dependencies"
    - "{{ environments_path }}/modulefiles"
    - "{{ local_path }}/software"
    - "{{ local_path }}/modulefiles"
    - "{{ pipelines_path }}/software"
    - "{{ pipelines_path }}/modulefiles"
    - "{{ quarantine_path }}/resources"
    - "{{ quarantine_path }}/software"
    - "{{ quarantine_path }}/modulefiles"
    - "{{ share_path }}/software"
    - "{{ share_path }}/modulefiles"
    - "{{ site_path }}"

# Install lmod
- name: Install lmod
  ansible.builtin.package:
    name: lmod
    state: present

# Copy lmod site config
- name: Copy lmod site configuration
  ansible.builtin.template:
    src: templates/SitePackage.j2
    dest: "{{ site_path }}/SitePackage.lua"
    owner: "{{ software_user }}"
    group: "{{ software_user }}"
    mode: u=rw,g=r,o=r

# Copy platform variable definitions
- name: Copy platform profile
  ansible.builtin.template:
    src: templates/platform.j2
    dest: "/etc/profile.d/platform.sh"
    owner: "{{ software_user }}"
    group: "{{ software_user }}"
    mode: u=rw,g=r,o=r

- name: Ensure default user umask is 027 in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK\s+'
    line: 'UMASK           027'
    state: present
