---

- name: Check users logged in
  hosts: workstations
  remote_user: "{{ admin_user }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: Check users logged in
    include_role:
      name: maintenance
      tasks_from: check_users_logged_in
