---

- name: Deploy av environment
  hosts: workstations
  remote_user: "{{ admin_user }}"
  become: true
  become_user: "{{ software_user }}"
  become_method: sudo
  tasks:
    - name: Install av
      include_role:
        name: environments
        tasks_from: av
