---

- name: Deploy RStudio
  hosts: workstations
  remote_user: "{{ admin_user }}"
  become: true
  become_user: "{{ software_user }}"
  become_method: sudo
  tasks:
    - name: Install RStudio
      include_role:
        name: local
        tasks_from: rstudio
