---

# See: https://ubuntu.com/blog/copy-fail-vulnerability-fixes-available
- name: Patch copy fail exploit (CVE-2026-31431)
  hosts: workstations
  remote_user: "{{ admin_user }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Patch copyfail
      include_role:
        name: maintenance
        tasks_from: patch_copyfail
