---

- name: Uninstall neuroansible-installed system MODULEPATH profile
  hosts: workstations
  remote_user: "{{ admin_user }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Uninstall neuroansible-installed system MODULEPATH profile
      include_role:
        name: maintenance
        tasks_from: uninstall_neuroansible_system_modulepaths



